name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag nodidevimg:latest
    - run: RUNNER_TRACKING_ID="" && docker run -d -e TOKEN=${{ secrets.TOKEN }} -e MONGO_URI=${{ secrets.MONGO_URI }} nodidevimg